FROM python:3.8.12-slim-buster

# That's correct. By default, Ubuntu installs recommended but not suggested packages. With --no-install-recommends, only the main dependencies (packages in the Depends field) are installed.
# &&\ means multiline 
# apt-get update: used to update the package index files on the system
# apt-get install force these packages to install
RUN apt-get update &&\ 
    apt-get install -y --no-install-recommends wget &&\
    rm -rf /var/lib/apt/lists/* &&\
    pip install --no-cache-dir transformers[torch] uvicorn fastapi

# adds the script defining the QA model to docker
COPY dl_model.sh .

# Downloads the required QA model
RUN bash dl_model.sh
    
# copies the app files to the docker image
COPY app/ app/

# runs our application at the start of the docker image
CMD ["python", "app/main.py"]